### ISSUE TITLE
Plugin is injecting `pluginPosts` tag, which is supposed to be for testing, into all collections

### ISSUE THREAD

**Issue by grempe** [brob/eleventy-plugin-blog-tools#7]
I was scratching my head trying to figure out why I all of a sudden had a new tag `pluginPosts` being added to my collections. I saw it pop up on my 'tags' page for my blog index and I knew it wasn't coming from my code.

I searched on all of GitHub and it pointed me right at the culprit:

https://github.com/brob/eleventy-plugin-blog-tools/blob/master/.eleventy.js#L20

I suspect you had this in there for testing purposes but now its polluting the collections of every user of this plugin.

Cheers

**Comment by brob** [comment]
Good catch! I changed the way I do testing and forgot to come back to this plugin!

Testing is refactored. Latest version should remove that extra tag 0.3.1

**Comment by grempe** [comment]
Great! Thanks.
