### ISSUE TITLE
README says 'YouTube' when it should say 'Vimeo'

### ISSUE THREAD

**Issue by grempe** [brob/eleventy-plugin-blog-tools#8]
Typo in the Vimeo code description. Replace YouTube with Vimeo:

`The YouTube shortcode takes a Vimeo video ID and creates the markup for a fluidly-responsive Vimeo embed.`

https://github.com/brob/eleventy-plugin-blog-tools#vimeo

**Comment by brob** [comment]
Thanks for the catch. This is fixed
